language: java
sudo: false

jdk:
- oraclejdk8

install: true

matrix:
  fast_finish: true

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/jvm'
  - '$HOME/maven'

after_success:
  - mvn cobertura:cobertura -Dcobertura.aggregate=true -Dcobertura.report.format=xml coveralls:report