language: java
sudo: false

jdk:
- oraclejdk8

install: true

script: "mvn cobertura:cobertura -Dcobertura.aggregate=true -Dcobertura.report.format=html"

matrix:
  fast_finish: true

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/jvm'
  - '$HOME/maven'

notifications:
  email: false