language: java
sudo: false

jdk:
- oraclejdk8

install: true
script: ./travis.sh
env:
  matrix:
  - TEST=ci
  - TEST=plugin SQ_VERSION=6.7
  - TEST=plugin SQ_VERSION=7.0
  - TEST=plugin SQ_VERSION=7.1
  - TEST=plugin SQ_VERSION=7.2

matrix:
  fast_finish: true


before_cache:
# remove all the artifacts that are installed in local repo because of mvn deploy
- rm -rf $HOME/.m2/repository/org/sonarsource/java
- find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar'
  - '$HOME/jvm'
  - '$HOME/maven'
notifications:
  email: false